import argparse
import json
import os
import sys
from collections import Counter


def load_report(report_path):
    if not os.path.isfile(report_path):
        print(f"Error: Report file '{report_path}' does not exist.")
        sys.exit(1)

    with open(report_path, "r") as f:
        return json.load(f)


def compute_stats(report):
    total_images = len(report)
    total_detections = 0
    object_counter = Counter()
    confidence_sums = {}
    confidence_counts = {}

    for image_name, detections in report.items():
        total_detections += len(detections)
        for det in detections:
            name = det["name"]
            confidence = det["confidence"]
            object_counter[name] += 1
            confidence_sums[name] = confidence_sums.get(name, 0.0) + confidence
            confidence_counts[name] = confidence_counts.get(name, 0) + 1

    avg_confidence = {
        name: round(confidence_sums[name] / confidence_counts[name], 2)
        for name in confidence_sums
    }

    most_common = object_counter.most_common()

    return {
        "total_images": total_images,
        "total_detections": total_detections,
        "unique_objects": len(object_counter),
        "avg_detections_per_image": round(total_detections / total_images, 2) if total_images else 0,
        "object_counts": dict(most_common),
        "avg_confidence_per_object": dict(sorted(avg_confidence.items())),
        "most_common_object": most_common[0][0] if most_common else None,
        "least_common_object": most_common[-1][0] if most_common else None,
    }


def print_stats(stats):
    print("=" * 50)
    print("  Detection Report Statistics")
    print("=" * 50)
    print(f"  Total images analysed  : {stats['total_images']}")
    print(f"  Total detections       : {stats['total_detections']}")
    print(f"  Unique object types    : {stats['unique_objects']}")
    print(f"  Avg detections / image : {stats['avg_detections_per_image']}")
    print(f"  Most common object     : {stats['most_common_object']}")
    print(f"  Least common object    : {stats['least_common_object']}")
    print("-" * 50)
    print("  Object counts:")
    for obj, count in stats["object_counts"].items():
        avg_conf = stats["avg_confidence_per_object"].get(obj, "N/A")
        print(f"    {obj:20s}  count={count:4d}  avg_confidence={avg_conf}%")
    print("=" * 50)


def main():
    parser = argparse.ArgumentParser(
        description="Show aggregate statistics from a JSON detection report"
    )
    parser.add_argument(
        "--input",
        type=str,
        default="report.json",
        help="Path to the JSON report generated by report.py (default: report.json)",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Optional path to save statistics as JSON",
    )
    args = parser.parse_args()

    report = load_report(args.input)
    stats = compute_stats(report)
    print_stats(stats)

    if args.output:
        with open(args.output, "w") as f:
            json.dump(stats, f, indent=2)
        print(f"\nStatistics saved to '{args.output}'.")


if __name__ == "__main__":
    main()
